### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by RyanTheAllmighty** [RyanTheAllmighty/nestjs-rate-limiter#12]
I created this package when I was myself using NestJS.

I am no longer using it, so this package is being neglected.

If anyone who has an active fork, or has other packages for nestjs on their GitHub account and wants the npm package name, please let me know below.

I don't like squatting on a package that I have no intentions to update and keep active

**Comment by ozkanonur** [comment]
@RyanTheAllmighty I am up for it, I have forked this package to make support fastify projects. But I would like to make this package supporting fastify and express in the same time therefore we wont need to install forked ones no more. I have a prod-level Nest application and I am using this package there. So I can actively maintain this with no issue.

**Comment by RyanTheAllmighty** [comment]
@ozkanonur excellent.

I can transfer the repo, or you can start fresh or use the fork, I honestly don't mind.

If you also give me your NPM username I'll transfer the package over to you.

**Comment by ozkanonur** [comment]
> @ozkanonur excellent.
> 
> I can transfer the repo, or you can start fresh or use the fork, I honestly don't mind.
> 
> If you also give me your NPM username I'll transfer the package over to you.

Its better if you can transfer so I can check the previous commits if I need to.
Npm username: onurrozkaan

**Comment by RyanTheAllmighty** [comment]
Alright transfers done. Hopefully this package can get better now it could be maintained :)

Thanks for volunteering to take it over

**Comment by RyanTheAllmighty** [comment]
Not sure how exactly NPM transfers happen, but feel free to remove me from the package once you've managed to login and get access to it.

**Comment by ozkanonur** [comment]
> Not sure how exactly NPM transfers happen, but feel free to remove me from the package once you've managed to login and get access to it.

It hapened with no issue, no need to remove you its all okay mate.
